import "./globals.css";
import type { Metadata } from "next";
import Provider from "./Provider";

// export const metadata: Metadata = {
//   title: "ImmoScraper23",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <Provider>
        <body>
          <main className="h-screen mx-auto text-sub">
            <div className="p-[10%]">{children}</div>
          </main>
        </body>
      </Provider>
    </html>
  );
}
